--- 

- hosts: all  
  become: true
  tasks:
    - name: install apache2 and php packages for Ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution_version == "Ubuntu"

    - name:  install apache and php packages for Centos 
      dnf:
        name:
          - httpd
          - php
        state: latest
        pdate_cache: yes 
      when: ansible_distribution_version == "Centos"
